### ISSUE TITLE
Add music

### ISSUE THREAD

**Issue by thewolf87** [too-mauro/Mr-Marshmallow#1]
Add music commands please

**Comment by too-mauro** [comment]
Thanks for the feedback! I'll consider adding music commands as soon as I publish v0.8.

**Comment by too-mauro** [comment]
Thanks for the feedback! I'll consider adding new music features as soon as the next feature update (v0.8) drops.

**Comment by too-mauro** [comment]
Hiya! I'm going to be including some music commands with the next major update, v0.9. Hang tight and thanks again for the request!
